export const ss = {
  wrap: {
    position: "relative", display: "flex", flexDirection: "column",
    height: "100vh", minHeight: "100vh", background: "transparent",
    color: "var(--text-1)", fontFamily: "'Inter',system-ui,sans-serif",
    overflow: "hidden", zIndex: 1,
  },
  topbar: {
    display: "flex", alignItems: "center", gap: "10px",
    padding: "0 20px", height: "58px",
    background: "var(--bg-glass-strong)",
    backdropFilter: "blur(28px) saturate(190%)",
    WebkitBackdropFilter: "blur(28px) saturate(190%)",
    borderBottom: "1px solid var(--border-mid)",
    flexShrink: 0, position: "sticky", top: 0, zIndex: 50,
  },
  sidebar: {
    width: "230px",
    background: "var(--bg-glass-strong)",
    backdropFilter: "blur(28px) saturate(190%)",
    WebkitBackdropFilter: "blur(28px) saturate(190%)",
    borderRight: "1px solid var(--border-mid)",
    display: "flex", flexDirection: "column",
    flexShrink: 0, overflowY: "auto",
    position: "relative", zIndex: 10,
  },
  main: {
    flex: 1, overflowY: "auto", padding: "28px 32px",
    scrollbarWidth: "thin", scrollbarColor: "var(--border-mid) transparent",
    position: "relative", zIndex: 1,
  },
  tableScroll: { overflowX: "auto", WebkitOverflowScrolling: "touch" },
  card: {
    background: "rgba(18, 10, 10, 0.68)",
    backdropFilter: "blur(18px) saturate(150%)",
    WebkitBackdropFilter: "blur(18px) saturate(150%)",
    border: "1px solid var(--border-mid)",
    borderRadius: "var(--r-lg)", padding: "18px",
    transition: "all 0.25s var(--ease-out)",
    position: "relative", overflow: "hidden",
    boxShadow: "0 4px 20px rgba(0,0,0,0.3)",
  },
  cardHover: { transition: "all 0.3s var(--ease-out)" },
  muted: { color: "var(--text-2)", fontSize: "12px", letterSpacing: "0.01em" },
  label: {
    color: "var(--text-3)", fontSize: "10px", textTransform: "uppercase",
    letterSpacing: "0.10em", fontWeight: 700, marginBottom: "6px",
  },
  btn: {
    padding: "8px 16px", borderRadius: "var(--r-sm)", border: "none",
    cursor: "pointer", fontSize: "12px", fontWeight: 700,
    transition: "all 0.18s var(--ease-out)", fontFamily: "inherit",
    display: "inline-flex", alignItems: "center", gap: "6px",
    justifyContent: "center", letterSpacing: "0.03em",
  },
  input: {
    background: "rgba(255,255,255,0.05)",
    border: "1px solid var(--border-mid)",
    borderRadius: "var(--r-sm)", color: "var(--text-1)",
    padding: "9px 12px", fontSize: "13px", outline: "none",
    width: "100%", boxSizing: "border-box",
    transition: "all 0.2s", fontFamily: "inherit",
  },
  sectionTitle: {
    display: "flex", justifyContent: "space-between", alignItems: "flex-start",
    marginBottom: "24px", gap: "16px", flexWrap: "wrap",
  },
};
